### PR TITLE
Feat/top level firebase

### PR DESCRIPTION
**Pull request by Kalk88**
## **Description**
Add a top level firebase configuration. This allows us to run everything
that is hosted on firebase locally with firebase serve. This will also
enable us to migrate the backend from app-engine to cloud functions in
future reviews, and stop using docker for development.

BREAKING CHANGE: 🧨 subfolder firebase configurations

<Please include a summary of the change and which issue is fixed.>

<Please also include relevant motivation and context.>

## **How to test?**
Try firebase serve and test the app locally. You might have to run npm install in client and server/functions. 
<Please describe the tests that you ran to verify your changes.>

<Provide instructions so we can reproduce.>

<Please also list any relevant details for your test configuration>
<List any dependencies that are required for this change.>

### CODE REVIEW

**Comment by PiddePannkauga** [comment]
Cannot run firebase serve
Error: Cannot find module '/home/pidde/GrowBud/server/functions/package.json'

**Comment by Kalk88** [comment]
I have one though... Maybe its a git ignore somewhere

**Comment by PiddePannkauga** [comment]
Please elaborate on the testing instructions. See my image for error message I recieve.
image
I have the latest changes

**Comment by Kalk88** [comment]
There is no pre "serve" hook sadly so, you have to run npm run build in the server/functions folder. I'll update the readme

**Pull request merged**
